### ISSUE TITLE
打开localhost:8080怎么是个目录结构啊？

### ISSUE THREAD

**Issue by yzf1116** [guzhongren/Tutorial-of-AGS_API-for-4.X-Development#2]

**Comment by guzhongren** [comment]
这个。。。。 你需要一点web基础。用http://localhost:8080/view打开吧

**Comment by yzf1116** [comment]
想向你咨询一下关于4.x版本的聚合图层是怎么实现的？

**Comment by guzhongren** [comment]
不知道你要哪种效果，在这推荐两种
1. 图幅框
    建立虚拟的合适的图幅框，计算每个图幅框内包含的要素，然后统计符号化实现
2. 行政区划
   方法和上面一样，只是统计区域为行政区划

**Comment by yzf1116** [comment]
统计图层个数，然后聚合在一起
![1509945695068](https://user-images.githubusercontent.com/13129167/32426499-69f9665a-c280-11e7-8950-4af6d6f2ed48.jpg)

**Comment by guzhongren** [comment]
图层个数？？  不明觉厉  
QQ说吧，315390030
